package exception21;
/*
 finally절 : 예외가 발생하든 안하든 실행하고자 하는 구문을 기술
 
 1) try ~ catch절 : 예외 직접처리
 2) try ~ catch~finally절 : 예외 직접 처리후 반드시 실행할 문장도 처리
 3) try ~ finally절 : 예외는 던지고(throws) 예외가 발생하든 안하든 반드시 실행할 문장 처리
 
 #finally절 안에 있는 명령문은 return문을 만나더라도 실행됨.
 	단, System.exit(0)를 만나면 당연히 실행 안됨
 */
public class ExceptionFinallyApp {

	public static void main(String[] args) {
		

	}//////main

}///////class
